import { ICatalogItem } from "../interfaces/ICatalogItem";

export const sampleItems : ICatalogItem[] = [
  {
    "uniqueId": "98906928",
    "name": "Zappos Sweater",
    "description": "Ethically designed, naturally sourced sweater",
    "price": 59.99,
    "image": "/assets/ZapposSweater.png",
    "quantity": 1,
  },
  {
    "uniqueId": "20873149",
    "name": "Fur Coat",
    "description": "Wonderfully Created Fur Coat",
    "price": 64.99,
    "image": "/assets/FurCoat.png",
    "quantity": 1,
  },
  {
    "uniqueId": "21731257",
    "name": "Fluffy Slippers",
    "description": "Specially designed slippers for those cold, winter mornings!",
    "price": 29.99,
    "image": "/assets/flufflyslippers.png",
    "quantity": 1,
  },
  {
    "uniqueId": "93475940",
    "name": "Sorel Boots",
    "description": "The perfect blend of comfy & rugged in one style!",
    "price": 79.99,
    "image": "/assets/SorelBoots.png",
    "quantity": 1,
  },
  {
    "uniqueId": "23309267",
    "name": "Furnace Sweater",
    "description": "Where ingenuity and comfort come together, try this product especially designed for those cold days!",
    "price": 99.99,
    "image": "/assets/FurnaceSweater.png",
    "quantity": 1,
  },  
  {
    "uniqueId": "52845575",
    "name": "Navy Blue Fleece Sweater",
    "description": "Extra soft, sports fleece designed for male & female athletes",
    "price": 39.99,
    "image": "/assets/blueSweater.png",
    "quantity": 1,
  },
  {
    "uniqueId": "57809812",
    "name": "Light Blue Sweatshirt",
    "description": "Custom made sweatshirt",
    "price": 49.99,
    "image": "/assets/menSweater.png",
    "quantity": 1,
  },
  {
    "uniqueId": "94282052",
    "name": "Loafers",
    "description": "Extra soft, slip on loafer",
    "price": 23.99,
    "image": "/assets/loafer.png",
    "quantity": 1,
  },
  {
    "uniqueId": "54115891",
    "name": "Blue Jeans",
    "description": "Custom tailored jeans designed for outer wear",
    "price": 49.99,
    "image": "/assets/jeans.png",
    "quantity": 1,
  },
  {
    "uniqueId": "28545165",
    "name": "Black Hoodie",
    "description": "Black Hoodie",
    "price": 19.99,
    "image": "/assets/hoodie.png",
    "quantity": 1,
  }
];